const PROGRAM={name:"FULL-BODY-TITAN HYBRID v5.6",subtitle:"MAXIMAL HYPERTROPHY",restDays:["Tisdag","Torsdag","Lördag","Söndag"],days:[
{id:"pass-1",short:"PASS 1",focus:"Quads Overload + Antagonist Chest/Back + Triceps",ex:[
["barbell_deep_squat","Olympisk knäböj med skivstång",4,8,"T",180],
["barbell_bench_press","Bänkpress med skivstång",4,8,"T",180,null,{sets:4,reps:8,kg:82,rir:0,note:"0 rir"}],
["leg_extension_machine","Maskin Bensträckning",4,12,"S",120,null,{sets:4,reps:12,kg:40,rir:0}],
["lat_pulldown","Kabel Latsdrag",4,10,"T",120],
["machine_pec_fly","Maskin Sittande Flyes",4,12,"S",120,null,{sets:2,reps:12,kg:36}],
["seated_cable_row","Sittande kabelrodd",4,10,"T",120],
["dumbbell_lateral_raise","Stående sidolyft med hantlar",5,15,"S",90,null,{sets:3,reps:15,kg:26,rir:1}],
["overhead_cable_triceps_extension","Kabel triceps extension över huvudet med rep",4,12,"S",90]]},
{id:"pass-2",short:"PASS 2",focus:"Posterior Chain + Incline Press + Back & Arm Overload",ex:[
["romanian_deadlift","Stång rumänskt marklyft",4,8,"T",180],
["incline_dumbbell_press","Hantelpress på incline bänk",4,10,"T",120],
["straight_arm_pulldown","Latsdrag med raka armar i kabel",3,12,"S",90],
["facepulls","Kabelstående ansiktsdrag (rep)",5,15,"S",90],
["dumbbell_lying_leg_curl","Liggande hamstringcurl med hantlar",4,12,"S",90],
["incline_dumbbell_biceps_curl","Hantelbicepscurl på incline bänk",4,12,"S",90],
["two_hand_lying_dumbbell_triceps_extension","Liggande hanteltricepsförlängning",3,12,"S",90],
["hammer_curl_rope","Kabelhammarcurl med rep",4,12,"S",90]]},
{id:"pass-3",short:"PASS 3",focus:"Unilateral Quads + Upper Body Power + Arms, Calves & Core",ex:[
["bulgarian_split_squat","Hantelbulgarisk splitknäböj",4,10,"T",120],
["larsen_press","Hantel Larsen Press",4,10,"T",120],
["reverse_grip_straight_back_seated_high_row","Sittande hög kabelrodd med rak rygg och omvänt grepp",4,10,"T",120],
["close_grip_bench_press","Bänkpress med skivstång och smalt grepp",4,10,"T",120],
["seated_dumbbell_lateral_raise","Sittande hantellyft åt sidan",4,15,"S",0,"A"],
["incline_rear_delt_flyes","Liggande hantellyft åt sidan bakåt",4,15,"S",150,"A"],
["standing_calf_raise","Skivstång Vadlyft på Golvet",5,12,"S",90],
["lying_leg_raise_flat_bench","Liggande Benlyft på Platt Bänk",3,15,"S",90],
["preacher_cable_hammer_curl","Kabel rep hammare predikantcurl",4,12,"S",0,"B"],
["rope_cable_pushdown","Kabel pushdown med rep",4,12,"S",150,"B"]]}]};
const app=document.querySelector("#app"); let selected=0,session=null,tick=null,restTick=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const exObj=a=>({id:a[0],name:a[1],sets:a[2],reps:a[3],tempo:a[4],rest:a[5],superset:a[6]||null,previous:a[7]||null});
PROGRAM.days.forEach(d=>d.ex=d.ex.map(exObj));
const totalSets=d=>d.ex.reduce((n,e)=>n+e.sets,0);
function shell(body){return '<div class="app"><header class="topbar"><div class="brand"><span class="mark"><i></i><i></i><i></i><i></i></span>CORTEX <span class="proto">UX-PROTOTYP</span></div></header>'+body+'</div>'}
function previous(e){if(!e.previous)return '<div class="previous nohist">Ingen tidigare data i prototypen</div>';let p=e.previous;return '<div class="previous">Senast: '+p.sets+'×'+p.reps+'×'+p.kg+' kg'+(p.rir!=null?' · RIR '+p.rir:'')+'</div>'}
function startScreen(){let d=PROGRAM.days[selected];app.innerHTML=shell('<main class="content"><section class="hero"><div class="eyebrow">FULL-BODY-TITAN · V5.6</div><h1>'+PROGRAM.subtitle+'</h1><p>'+d.focus+'</p></section><div class="tabs">'+PROGRAM.days.map((x,i)=>'<button class="tab '+(i===selected?'active':'')+'" data-day="'+i+'">'+x.short+'</button>').join('')+'</div><div class="stats"><div class="stat"><b>'+d.ex.length+'</b><span>övningar</span></div><div class="stat"><b>'+totalSets(d)+'</b><span>planerade set</span></div><div class="stat"><b>104</b><span>set / vecka</span></div></div><div class="exercise-list">'+d.ex.map((e,i)=>'<div class="exercise-card"><div class="num">'+String(i+1).padStart(2,"0")+'</div><div class="exercise-main"><div class="exercise-name">'+esc(e.name)+(e.superset?'<span class="superset">SUPERSET '+e.superset+'</span>':'')+'</div><div class="meta">'+e.sets+' × '+e.reps+' · '+(e.tempo==="T"?"Tungt":"Strikt")+' · '+(e.rest?e.rest+'s vila':'direkt vidare')+'</div>'+previous(e)+'</div></div>').join('')+'</div><button id="start" class="primary">STARTA '+d.short+'</button><p class="small" style="text-align:center">Prototypdata sparas endast lokalt i den här webbläsaren.</p></main>');
document.querySelectorAll("[data-day]").forEach(b=>b.onclick=()=>{selected=+b.dataset.day;startScreen()});document.querySelector("#start").onclick=startSession}
function startSession(){let d=PROGRAM.days[selected];session={day:selected,started:Date.now(),active:0,ended:null,ex:d.ex.map(e=>({...e,notes:"",rows:Array.from({length:e.sets},()=>({reps:e.reps,kg:e.previous?.kg??"",rir:e.previous?.rir??"",done:false,at:null}))})),restEnd:null};save();renderSession();runTimers()}
function save(){if(session)localStorage.setItem("cortex-live-prototype",JSON.stringify(session))}
function fmt(sec){sec=Math.max(0,Math.floor(sec));return String(Math.floor(sec/60)).padStart(2,"0")+":"+String(sec%60).padStart(2,"0")}
function elapsed(){return (Date.now()-session.started)/1000}
function doneCount(){return session.ex.reduce((n,e)=>n+e.rows.filter(r=>r.done).length,0)}
function allCount(){return session.ex.reduce((n,e)=>n+e.rows.length,0)}
function renderSession(){let d=PROGRAM.days[session.day],e=session.ex[session.active],pct=100*doneCount()/allCount();app.innerHTML=shell('<main class="content"><div class="active-head"><div><div class="eyebrow">'+d.short+' · PÅGÅENDE</div><div class="clock" id="clock">'+fmt(elapsed())+'</div></div><button class="secondary danger" id="finish">Avsluta</button></div><div class="progress"><i style="width:'+pct+'%"></i></div><div class="nav-exercises">'+session.ex.map((x,i)=>'<button data-ex="'+i+'" class="'+(i===session.active?'active ':'')+(x.rows.every(r=>r.done)?'complete':'')+'">'+(i+1)+'</button>').join('')+'</div><section class="focus-card"><div class="small">ÖVNING '+(session.active+1)+' / '+session.ex.length+'</div><h2>'+esc(e.name)+'</h2><div class="badges"><span class="badge">'+e.sets+'×'+e.reps+'</span><span class="badge">'+(e.tempo==="T"?"Tungt":"Strikt")+'</span><span class="badge">'+(e.rest?e.rest+'s vila':'ingen vila')+'</span>'+(e.superset?'<span class="badge">Superset '+e.superset+'</span>':'')+'</div><div class="history"><div class="history-title">Senaste registrerade</div>'+(e.previous?'<strong>'+e.previous.sets+'×'+e.previous.reps+'×'+e.previous.kg+' kg'+(e.previous.rir!=null?' · RIR '+e.previous.rir:'')+'</strong>'+(e.previous.note?'<div class="small">'+esc(e.previous.note)+'</div>':''):'<strong class="nohist">Ingen känd historik</strong>')+'</div><div class="sets"><div class="set-head"><span>Set</span><span>Reps idag</span><span>Kg idag</span><span>Klar</span></div>'+e.rows.map((r,i)=>'<div class="set-row '+(r.done?'done':'')+'" data-row="'+i+'"><div class="set-n">'+(i+1)+'</div><input class="field reps" inputmode="numeric" value="'+esc(r.reps)+'"><input class="field kg" inputmode="decimal" value="'+esc(r.kg)+'"><button class="check">'+(r.done?'✓':'○')+'</button></div>').join('')+'</div><div class="rir-row"><label>RIR för nästa/aktuellt set</label><input id="rir" class="field" inputmode="numeric" value="'+esc(e.rows.find(r=>!r.done)?.rir??e.rows.at(-1)?.rir??"")+'" placeholder="—"></div><textarea id="notes" class="notes" placeholder="Notering för övningen…">'+esc(e.notes)+'</textarea></section><div class="footer-actions"><button id="prevEx" class="secondary">← Föregående</button><button id="nextEx" class="secondary">Nästa →</button></div></main>'+restHtml());
bindSession()}
function restHtml(){if(!session.restEnd||session.restEnd<=Date.now())return "";return '<aside class="rest"><div class="rest-inner"><div><div class="small">VILOTIMER</div><div id="restTime" class="rest-time">'+fmt((session.restEnd-Date.now())/1000)+'</div></div><button id="minus">−5</button><button id="plus">+5</button><button id="skip">Hoppa</button></div></aside>'}
function bindSession(){document.querySelectorAll("[data-ex]").forEach(b=>b.onclick=()=>{syncFields();session.active=+b.dataset.ex;save();renderSession()});document.querySelectorAll(".set-row").forEach(row=>{let i=+row.dataset.row;row.querySelector(".check").onclick=()=>toggleSet(i)});document.querySelector("#notes").oninput=e=>{session.ex[session.active].notes=e.target.value;save()};document.querySelector("#prevEx").onclick=()=>move(-1);document.querySelector("#nextEx").onclick=()=>move(1);document.querySelector("#finish").onclick=finish;document.querySelector("#minus")?.addEventListener("click",()=>adjustRest(-5));document.querySelector("#plus")?.addEventListener("click",()=>adjustRest(5));document.querySelector("#skip")?.addEventListener("click",()=>{session.restEnd=null;save();renderSession()})}
function syncFields(){document.querySelectorAll(".set-row").forEach(row=>{let r=session.ex[session.active].rows[+row.dataset.row];r.reps=row.querySelector(".reps").value;r.kg=row.querySelector(".kg").value});let rir=document.querySelector("#rir")?.value;if(rir!==undefined){let target=session.ex[session.active].rows.find(r=>!r.done);if(target)target.rir=rir}save()}
function toggleSet(i){syncFields();let e=session.ex[session.active],r=e.rows[i];r.done=!r.done;r.at=r.done?Date.now():null;if(r.done&&e.rest>0)session.restEnd=Date.now()+e.rest*1000;else if(!r.done)session.restEnd=null;save();renderSession()}
function move(delta){syncFields();session.active=Math.max(0,Math.min(session.ex.length-1,session.active+delta));save();renderSession()}
function adjustRest(sec){session.restEnd=Math.max(Date.now(),session.restEnd+sec*1000);save();renderSession()}
function runTimers(){clearInterval(tick);tick=setInterval(()=>{if(!session||session.ended)return;let c=document.querySelector("#clock");if(c)c.textContent=fmt(elapsed());let r=document.querySelector("#restTime");if(r&&session.restEnd){let left=(session.restEnd-Date.now())/1000;if(left<=0){session.restEnd=null;save();renderSession()}else r.textContent=fmt(left)}},500)}
function finish(){syncFields();if(!confirm("Avsluta passet och visa sammanfattning?"))return;session.ended=Date.now();session.restEnd=null;save();renderSummary()}
function renderSummary(){let d=PROGRAM.days[session.day],done=doneCount(),vol=session.ex.reduce((sum,e)=>sum+e.rows.filter(r=>r.done).reduce((s,r)=>s+(Number(r.reps)||0)*(Number(r.kg)||0),0),0);app.innerHTML=shell('<main class="content summary"><div class="eyebrow">PASS SLUTFÖRT</div><div class="big">✓</div><h1>'+d.short+'</h1><p>'+d.focus+'</p><div class="summary-card"><div class="stats"><div class="stat"><b>'+done+'</b><span>loggade set</span></div><div class="stat"><b>'+fmt((session.ended-session.started)/1000)+'</b><span>tid</span></div><div class="stat"><b>'+Math.round(vol)+'</b><span>kg volym</span></div></div><div class="small">Detta är endast prototypens lokala sammanfattning. Ingen data skickas till Cortex.</div></div><button class="primary" id="new">TILL STARTEN</button></main>');document.querySelector("#new").onclick=()=>{localStorage.removeItem("cortex-live-prototype");session=null;startScreen()}}
const saved=localStorage.getItem("cortex-live-prototype");if(saved){try{session=JSON.parse(saved);selected=session.day;if(session.ended)renderSummary();else{renderSession();runTimers()}}catch{startScreen()}}else startScreen();